---
title: "Fundamentals of Study Design"
output: 
  html_document:
    includes:
      in_header:
        - header.html 
        - header-tracker.html
---

*Fundamentals of Study Design* is a six-week short course I originally developed in Spring 2019 as part of the [Biostatistics, Epidemiology, and Research Design (BERD)](https://cctsi.cuanschutz.edu/resources/berd) core at the University of Colorado Anschutz Medical Campus. It is a course for those wanting to become acquainted with basic clinical trial methodology, either to broaden their knowledge of public health and clinical research, or to obtain a basis for more advanced study of the design and conduct of clinical trials. Throughout the six weeks we will introduce clinical trial design in the context of epidemiological concepts, cover various topics in the design and conduct of clinical trials, and profile clinical trials that illustrate these issues.  

The schedule of topics by week include:

* Study Design History and Comparisons
* Identifying the Research Hypotheses and Study Population, Collecting Data
* Exploration of Clinical Trial Designs I
* Exploration of Clinical Trial Designs II and Analyzing the Data
* Sample Size, Power, and Sequential Monitoring
* Novel Study Designs and Reporting Results

This course is typically offered early in the fall semester on the University of Colorado Anschutz Medical Campus. **For 2023 the course will be offered virtually and is scheduled on Wednesday evenings from 4 PM to 6 PM from September 6-October 10.** For more information and how to sign up you can visit the [Center for Innovative Design and Analysis' short course page](https://coloradosph.cuanschutz.edu/research-and-practice/centers-programs/cida/learning/biostatistics-short-courses#ac-fundamentals-of-study-design-2).

